export const DEFAULT_PLACE = {
    name:"Johannesburg",
    place_id:"johannesburg",
    adm_area1:"Gauteng",
    adm_area2:"City of Johannesburg Metropolitan Municipality",
    country:"South Africa",
    lat:"26.20227S",
    lon:"28.04363E",
    timezone:"Africa/Johannesburg",
    type:"settlement",
  };
  export const MEASUREMENT_SYSTEMS = {
    AUTO: 'auto',
    METRIC: 'metric',
    UK: 'uk',
    US: 'us',
    CA: 'ca',
  };
  export const UNITS = {
    metric: {
      temperature: 'C',
      precipitation: 'mm/h',
      wind_speed: 'm/s',
      visibility: 'km',
      humidity: '%',
      uv_index: '',
      cloud_cover: '%',
    },
    us: {
      temperature: 'F',
      precipitation: 'in/h',
      wind_speed: 'mph',
      visibility: 'mi',
      humidity: '%',
      uv_index: '',
      cloud_cover: '%',
    },
    uk: {
      temperature: 'C',
      precipitation: 'mm/h',
      wind_speed: 'mph',
      visibility: 'mi',
      humidity: '%',
      uv_index: '',
      cloud_cover: '%',
    },
    ca: {
      temperature: 'C',
      precipitation: 'mm/h',
      wind_speed: 'km/h',
      visibility: 'km',
      humidity: '%',
      uv_index: '',
      cloud_cover: '%',
    },
  };